version: '3'

services:
  postgres:
    image: 'postgres:14.1'
    container_name: 'pg'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=tinyurl'

  app:
    build: ./
    container_name: 'tinyurl'
    ports:
      - "8080:8080"